### PR TITLE
MBS-6044: Fix scaling of big ggb applets by using scaling containers

### LINKED ISSUE #39: Größe der Geogebra-Dateien passt nicht
Liebe Community, habe leider in einen geschlossenen Thread geschrieben. Hier nun nochmal: 
Ich habe das selbe Problem wie Birgit Lackner - die hochgeladen ggbs in den Moodlefragen werden zu groß und manchmal auch zu klein angezeigt, die eingestellte Größe von 900 *500 wird ignoriert - nun habe ich diesen Post gefunden und https://github.com/mebis-lp/moodle-qtype_geogebra/commit/4712ae50470792c3bfaafa79c618bdf4d73ab11c heruntergeladen, aber moodle sagt, es gibt eine neuere Version des Plugins vom 310122. Ich habe ca 100 Geogebraübungen auf [www.mathe4alle.at](http://www.mathe4alle.at/), die nicht mehr gut gelöst werden können (bei manchen ist der StartButton nicht sichtbar (zu kleine Ansicht), andere können nicht abgeschlossen werden, weil etwas zugedeckt wird. 
Gibt es ein neueres Plugin oder irgendeine Idee? Oder welche Datei im GeogebraOrdner-in Questions-Types kann ich aktualisieren? 
image
Beim zweiten Bild sieht man den Startbutton nicht 
image
Ich wäre sehr dankbar für eine Lösung  Marlis Schedler

### PR DESCRIPTION
**Pull request by PhMemmel**
Closes #39 

This PR reworks the way of embedding the ggb applet with the correct size. We now use the `scaleContainerClass` attribute of the ggb api, see https://wiki.geogebra.org/en/Reference:GeoGebra_App_Parameters

I also added a resize listener which recalculates the width of the ggb scaling container whenever the browser window is being resized, so the ggb applet properly adapts to the container even if the window is being resized.

Major change: Now the complete applet is being scaled into the container by default. So for the ggb applet to properly fit in it needs to be saved with the correct size of the view.

In the second commit (8f2a148775816ed2dd538a15294aed487192eeca) I also added the possibility to manually overwrite the scaling container feature by specifying width and height manually. In this case no scaling container is being used, but the applet will have the given dimensions. If it does not fit into the quiz layout, horizontal scroll bars will be added so students will have access to all areas of the plugin and be able to enlarge the screen to make the applet fit. Leaving width and height empty or 0 will fall back to the scaling container.

Also note: This PR also adds the newly minified JS files introduced in the latest 3.11 changes and adds two fields in the table.

### CODE REVIEW

**Comment by mputzi** [comment]
I tested the new scaling method in moodle 4, it works flawless. Rescaling works, too.

But since in standard Boost theme the `region-main-box` div element hast a fixed max-width of 814px GeoGebra files with a much larger view (e.g. when originally edited in fullscreen mode) are scaled down so much they get unusable.

Screenshot of too much scaling

I think, we should include a warning as to the author of the question whenever a ggb file is uploaded with a width larger than 814px or about 900px.

File: amd/src/ggbq.js [hunk 1]
```diff
@@ -95,8 +108,24 @@ define(['jquery', '//www.geogebra.org/apps/deployggb.js'], function ($, GGBApple
...
+                // of the plugin instance. Form validation of the settings asserts that both width and height are being set.
+                parameters.width = ggbDataset.width;
+                parameters.height = ggbDataset.height;
+                // We need to use getElementsByClassName because colons are not allowed for jquery and Vanilla JS querySelector.
+                const scalingContainer = document.getElementsByClassName(scalingContainers[slot])[0];
+                // We should always find this container, just check to be extra safe.
+                if (scalingContainer) {
+                    // Width of the scaling container is being set after the applet has been loaded. So no need to specify it here.
+                    scalingContainer.style.overflowX = 'auto';
+                    scalingContainer.style.overflowY = 'hidden';
```
Comment (mputzi) [inline amd/src/ggbq.js:126]: Why is overflowY set to `'hidden'`? This prohibits the vertical scrollbar.
Is it for preventing scrolling issues on small screens?

File: amd/src/ggbq.js [hunk 2]
```diff
@@ -14,13 +14,24 @@ define(['jquery', '//www.geogebra.org/apps/deployggb.js'], function ($, GGBApple
...
     const resizeScalingContainer = () => {
         clearTimeout(resizeTimeout);
-        resizeTimeout = setTimeout(() => $(".ggbscalingcontainer").width($(".qtext").parent().parent().width(), 250));
+        resizeTimeout = setTimeout(
+            () => Object.values(scalingContainers).forEach((containerClass) => {
+                    // We need to use getElementsByClassName because colons are not allowed for jquery and Vanilla JS querySelector.
+                    const scalingContainer = document.getElementsByClassName(containerClass)[0];
+                    // We retrieve the formulation div container, because this gives us the correct width to adapt
+                    // the scaling container to.
+                    const formulationDivStyle = window.getComputedStyle(
```
Comment (mputzi) [inline amd/src/ggbq.js:30]: I would call the constant `qtextDivStyle`.

**Review by mputzi — APPROVED** [review]

File: amd/src/ggbq.js (hunk 1 above)
Comment (PhMemmel) [reply amd/src/ggbq.js:126]: In all cases I tested there was no need of it, because the containing container just grows to whatever height you set. If you have an example of parts of the applet being cut off, pls provide some.
Other reason is: I didn't really manage to make the scroll bar disappear in case of "nearly fitting it", so I disabled it completely

File: amd/src/ggbq.js (hunk 2 above)
Comment (PhMemmel) [reply amd/src/ggbq.js:30]: Well, it's not the qtext div, but the formulation div, see `parentElement.parentElement` in line 31

Comment (mputzi) [reply amd/src/ggbq.js:30]: Sorry, you're right. :+1:
